# Generated by Django 3.2.4 on 2021-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCSP_DNS_DJANGO', '0003_ocspresponseswrtasn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocspresponseswrtasn',
            name='ocsp_response',
        ),
        migrations.AddField(
            model_name='ocspresponseswrtasn',
            name='ocsp_response_as_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
