# Generated by Django 3.2.4 on 2021-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCSP_DNS_DJANGO', '0004_auto_20210625_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocspresponseswrtasn',
            old_name='asn',
            new_name='hop',
        ),
        migrations.AddField(
            model_name='ocspresponseswrtasn',
            name='mode',
            field=models.CharField(default='ASN', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ocspresponseswrtasn',
            name='country_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ocspresponseswrtasn',
            unique_together={('ocsp_url', 'serial', 'hop', 'mode')},
        ),
    ]
