# Generated by Django 3.2.4 on 2021-11-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCSP_DNS_DJANGO', '0005_auto_20210712_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocspresponseswrtasn',
            name='node_meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
